spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: test

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
